#name: Node.js Package
#
#on:
#  push:
#    branches:
#      - develop
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#      - uses: actions/setup-node@v3
#        with:
#          node-version: 18.15.0
#      - run: npm ci
#      - run: npm test
#
#  publish-gpr:
#    needs: build
#    runs-on: ubuntu-latest
#    permissions:
#      packages: write
#      contents: read
#    steps:
#      - uses: actions/checkout@v4
#      - uses: actions/setup-node@v3.4.1
#        with:
#          node-version: 18.15.0
#          registry-url: https://npm.pkg.github.com/
#      - run: npm ci
#      - run: npm publish --workspace packages/core
#        env:
#          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
#
